@base = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU2ODU4N2Q5LWRjNmQtNDI1Yi1iMGQ5LTI5ZjkzMmZjZDVlZSIsImFkbWluIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJhdmF0YXIiOiJhdmF0YXIucG5nIiwiaWF0IjoxNzE0NzUwNjMzLCJleHAiOjE3MTYwNDY2MzN9.3ak7Pn8TkRRt7S69-7qFtZ-Njhsn9ovts1Sks3nV9R8



###
POST {{base}}/signin HTTP/1.1
# Authorization: base {{token}}
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Admin123!"
}

###
POST {{base}}/address HTTP/1.1
Authorization: Barear {{token}}
Content-Type: application/json

{
    "username": "ahmedali",
    "mobile": 1000000000,
    "government": "0ffb83c6dd9b011c33f305c48ce06eb9",
    "city": "faq",
    "address": "مصر القديمه قسم الدقي العجوزه"
}

###
GET {{base}}/address HTTP/1.1
Authorization: Barear {{token}} 

###
GET {{base}}/government HTTP/1.1
Authorization: bearer {{token}}

###
GET {{base}}/cart HTTP/1.1
Authorization: b {{token}}


###
GET {{base}}/checkout HTTP/1.1
Authorization: be {{token}}

###
GET {{base}}/checkout/seller HTTP/1.1
Authorization: be {{token}}


###
GET {{base}}/checkout/seller/43ba1cd5-38c8-4a61-9dbb-4bf5fd6e0579 HTTP/1.1
Authorization: be {{token}}


###
GET {{base}}/checkout/seller/43ba1cd5-38c8-4a61-9dbb-4bf5fd6e0579 HTTP/1.1
Authorization: be {{token}}


###
GET {{base}}/checkout/seller/search/10012 HTTP/1.1
Authorization: be {{token}}
Content-Type: application/json


###
GET {{base}}/checkout/seller/getTotal/GovOrder HTTP/1.1
Authorization: be {{token}}
Content-Type: application/json


###
GET {{base}}/books/search/s  HTTP/1.1
Authorization: be {{token}}
# Content-Type: application/json



###
POST {{base}}/checkout HTTP/1.1
Authorization: b {{token}}



###
GET {{base}}/admin/users HTTP/1.1
Authorization: baerer {{token}}

###
GET {{base}}/admin/orders HTTP/1.1
Authorization: bearer {{token}}

###
GET {{base}}/admin/orders/order/f0300b8c-1642-4dd4-bae5-b1b4a450a38b HTTP/1.1
Authorization: bearer {{token}}

###
PATCH {{base}}/admin/orders/order/f0300b8c-1642-4dd4-bae5-b1b4a450a38b HTTP/1.1
Authorization: bearer {{token}}


{
    "status": "pending",
    "shipping": "30"
}


###
GET {{base}}/admin/dashboard HTTP/1.1
Authorization: {{token}}